### ISSUE TITLE
Loading should be replace by a PlaceHolder

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/betarena-ad-widget-main#4]
The loading widget information should be replaced by a PlaceHolder.

**Comment by migbash** [comment]
@jonsnowpt Just a placeholder? Like an `<image>` tag? Or do you have a design for a loading of the widget that I need to implement?

**Comment by jonsnowpt** [comment]
A place holder that simulates what is going to appear. There are a few for svelte with pre-defined geometries that can be adapted. If you need more information please ask.

**Comment by jonsnowpt** [comment]
Here is an example:

https://madewithsvelte.com/svelte-content-loader

**Comment by migbash** [comment]
I see, I understand, is there an `<svg>` I you want me to use for the loading animation with the `svelte-content-loader`? Or should I just use one from the `svelte-content-loader` examples for now?

**Comment by jonsnowpt** [comment]
You can use one from the examples that makes more sense.
